package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.25

import (
	"context"

	"github.com/rs/xid"
	"github.com/shota-tech/graphql/server/graph/model"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.CreateTaskInput) (*model.Task, error) {
	task := &model.Task{
		ID:     xid.New().String(),
		Text:   input.Text,
		Status: model.StatusTodo,
		UserID: input.UserID,
	}
	if err := r.TaskRepository.Store(ctx, task); err != nil {
		return nil, err
	}
	return task, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	user := &model.User{
		ID:   xid.New().String(),
		Name: input.Name,
	}
	if err := r.UserRepository.Store(ctx, user); err != nil {
		return nil, err
	}
	return user, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
